In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # 空间三维画图

In [2]:
uv=np.loadtxt('camera_uv.txt',dtype=np.int32)
xyz=np.loadtxt('camera_xyz.txt',dtype=np.float32)[:,0:3]
print(uv.shape)
print(xyz.shape)

(6570, 2)
(6570, 3)


In [3]:
%matplotlib auto
x=xyz[:,0]
y=xyz[:,1]
z=xyz[:,2]
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(x, y, z)
# 添加坐标轴(顺序是Z, Y, X)
ax.set_zlabel('Z')
ax.set_ylabel('Y')
ax.set_xlabel('X')
plt.show()

Using matplotlib backend: Qt5Agg


# 提取框内点晕并显示

In [4]:
# uv显示
u=uv[:,0]
v=uv[:,1]
print(u.min(),u.max(),u.max()-u.min())
print(v.min(),v.max(),v.max()-v.min())
plt.figure()
#设置X轴标签
plt.xlabel('X')
#设置Y轴标签
plt.ylabel('Y')
plt.scatter(u, v)
plt.show()

0 639 639
6 454 448


In [5]:
#已知uv，xyz。求对应框内的三维点云
print(uv[:,0].dtype)
print(uv[:,0].shape)
def get_one_pc(x1,x2,y1,y2):
    test=np.where((uv[:,0]>x1) & (uv[:,0]<x2) & (uv[:,1]>y1) & (uv[:,1]<y2))
    print(test)
    get_uv=uv[test]
    get_xyz=xyz[test]
    print(get_xyz)
    print(get_uv)
    
    plt.figure()
    plt.scatter(get_uv[:,0],get_uv[:,1])
    plt.show()
    x=get_xyz[:,0]
    y=get_xyz[:,1]
    z=get_xyz[:,2]
    fig = plt.figure()
    ax = Axes3D(fig)
    ax.scatter(x, y, z)
    # 添加坐标轴(顺序是Z, Y, X)
    ax.set_zlabel('Z', fontdict={'size': 15, 'color': 'red'})
    ax.set_ylabel('Y', fontdict={'size': 15, 'color': 'red'})
    ax.set_xlabel('X', fontdict={'size': 15, 'color': 'red'})
    plt.show()
    
get_one_pc(130,370,0,300)
get_one_pc(130,370,0,350)

int32
(6570,)
(array([ 946,  950,  952, ..., 4015, 4022, 4026]),)
[[-1.3560081e+00  2.3767713e-01  4.3345194e+00]
 [-1.3480393e+00  8.0105938e-02  4.3094025e+00]
 [-1.3396244e+00 -7.5398229e-02  4.2828684e+00]
 ...
 [-9.7469524e-02 -7.2141314e-01  4.1281028e+00]
 [-8.9266129e-02  1.2556267e-01  3.6967649e+00]
 [-8.6645082e-02 -1.8884600e-03  3.6670656e+00]]
[[131 298]
 [131 267]
 [131 236]
 ...
 [369 102]
 [369 280]
 [369 251]]
(array([ 942,  946,  950, ..., 4018, 4022, 4026]),)
[[-1.2914845e+00  3.7602779e-01  4.1259627e+00]
 [-1.3560081e+00  2.3767713e-01  4.3345194e+00]
 [-1.3480393e+00  8.0105938e-02  4.3094025e+00]
 ...
 [-8.7923110e-02  2.4250111e-01  3.5424223e+00]
 [-8.9266129e-02  1.2556267e-01  3.6967649e+00]
 [-8.6645082e-02 -1.8884600e-03  3.6670656e+00]]
[[131 329]
 [131 298]
 [131 267]
 ...
 [368 310]
 [369 280]
 [369 251]]


In [8]:
print(uv[:,0].dtype)
print(uv[:,0].shape)
def get_box_distance(x1,x2,y1,y2):
    test=np.where((uv[:,0]>x1) & (uv[:,0]<x2) & (uv[:,1]>y1) & (uv[:,1]<y2))
    get_uv=uv[test]
    get_xyz=xyz[test]
#     x=get_xyz[:,0]
#     y=get_xyz[:,1]
#     z=get_xyz[:,2]
    depth = np.sqrt(np.square(get_xyz[:, 0]) + np.square(get_xyz[:, 1]) + np.square(get_xyz[:, 2]))
    print(depth.min())
get_box_distance(130,370,0,300)
get_box_distance(130,370,0,350)

int32
(6570,)
2.73216
2.73216
